### ISSUE TITLE
Prepare package for ovi store

### ISSUE THREAD

**Issue by cip** [cip/WikiOnBoard#43]
1. Use UID assigned from Nokia. Done (0x20045592) 
2. Use UID  for symbian signed in installer wrapper. Done
3. Probably necessary to build with S^1 4.6.3, potentially necessary to use qt sdk instead of carbide. 
            (Potentiallly not working with  S60 FP1 then, separate builds necessary). 
           (Visible difference: no c:\adm path on S^1 4.6.3)
4. Check whether install over self-signed package works. (First install required removal of self-signed app, check this )
   Other?
   => See http://doc.qt.nokia.com/smart-installer-1.1/smartinstaller-packages.html,
   Ovi publish faq, http://www.developer.nokia.com/Community/Wiki/Guide_to_Publishing_Qt_Applications_to_the_Ovi_Store

**Comment by cip** [comment]
Now builds in qt sdk 1.1.2   as well. (Qt 4.6.3 S^1)
Does not work on N82. (Tested Qt Example trafficlight works , thus not directly related that sdk is S^1.)   

Qt 4.6.3 S^3 target not compiling. (Libraries compile (although some zimlib debug outs lead to errors). First error when compling wikionboard:    C:/QtSDK/Symbian/SDKs/Symbian3Qt463/epoc32/release/armv5/urel/QtScroller.lib(qtscroller.o): In function `__static_initialization_and_destruction_0':
   C:/Symbian/Carbide/workspace/kineticscroller/src/qtscroller.cpp:292: undefined reference to`__aeabi_atexit'

**Comment by cip** [comment]
- Built in qt creator using Qt 4.7.3 for Symbian^1  (Instead qt 4.6.3 for S^1) starting with version 0.0.52.

**Comment by cip** [comment]
Issue: Package name includes UID (Displayed during installation, and also in program manager)
Fixed.

**Comment by cip** [comment]
Version 1.0.0. uploaded to ovi publish

**Comment by cip** [comment]
Version 1.0.0. Published on 20.7.2011 to ovi store (http://store.ovi.com/content/148305)
